### ISSUE TITLE
Electrum Server: Verbindungsprobleme erzeugen hohe CPU-Auslastung und hohen Energieverbrauch

### ISSUE THREAD

**Issue by Wendel-BS** [DFXswiss/btc-wallet#142]
**Status**:
 🇩🇪  Wenn die DFX BTC Taro App geöffnet ist (und im Hintergrund läuft), belastet sie die CPU minimal; 
dementsprechend gering ist auch der Energiebedarf der App.

🇬🇧  When the DFX BTC Taro App is open (and running in the background), the CPU load is minimal; 
The power consumption of the application is correspondingly low.

**Problem**:
 🇩🇪  Seit Monaten leidet die DFX BTC Taro App an Verbindungsproblemen zum Electrum Server, 
was auch schon zu entsprechenden Fehlermeldungen geführt hat, welche inzwischen unterbunden werden.
Siehe hierzu Bilder und Videoclip im vorherigen GitHub-Issue:  https://github.com/DFXswiss/btc-wallet/issues/135

Das Verhindern der Fehlermeldungen hat aber leider das Hauptproblem 
(Verbindungsprobleme bzw. das Nicht-Wiederverbinden zum Electrum Server) nicht gelöst.

Sobald die Statusanzeige zwischen ‚verbunden‘ und ‚nicht verbunden‘ zu flackern beginnt, 
steigt offensichtlich die CPU-Last und der Energiebedarf, da die App ständig versucht eine Verbindung herzustellen.

Sobald die Statusanzeige dauerhaft auf ‚nicht verbunden‘ steht, 
wird der Rechner in Folge der CPU-Last und des Energieverbrauchs deutlich warm (fast heiß).

🇬🇧  The DFX BTC Taro app has been experiencing connection problems with the Electrum server for months, 
which has already led to error messages, which are now being prevented.
See pictures and video clip in the previous GitHub issue: https://github.com/DFXswiss/btc-wallet/issues/135

Unfortunately, preventing the error messages has not solved the main problem (connection problems or the inability to reconnect to the Electrum server).

As soon as the status bar starts to flicker between 'connected' and 'disconnected', 
CPU load and power consumption will naturally increase as the application constantly tries to connect.

Once the status indicator is permanently set to 'Not Connected', 
the computer will become very warm (almost hot) due to the CPU load and power consumption.

**Screenshots** :

![IMAGE 2024-11-06 19:33:30](https://github.com/user-attachments/assets/2da93b32-8155-41e0-99d5-9ba0a1c53631)
(Aktivitätsanzeige - Bild 1)  CPU-Auslastung

![IMAGE 2024-11-06 19:33:54](https://github.com/user-attachments/assets/396c482b-79f4-42fc-9a72-1c765354afc0)
(Aktivitätsanzeige - Bild 2)  Energiebedarf

![IMAGE 2024-11-06 19:34:13](https://github.com/user-attachments/assets/b4c0a152-0e89-4052-8acd-7e89c6c0cccc)

 🇩🇪  **Hinweise**:
Nach dem schließen der DFX BTC Taro App kühlt das MacBook innerhalb von Minuten schnell und deutlich ab.
Wird dann die DFX BTC Taro App neu gestartet, verbindet sie sich problemlos mit dem Electrum Server.
Dieses beschriebene Fehlerbild wurde bisher in der aktuellen Beta-Version 3 x beobachtet.
Nach einer 2 - 3 tägigen Laufzeit der App, ist das Fehlerbild bisher am Vormittag aufgetreten.

🇬🇧  **Hints & Notes**:
After closing the DFX BTC Taro App, the MacBook cools down quickly and significantly within minutes.
When the DFX BTC Taro App is then restarted, it connects to the Electrum server without any problems.
This error pattern has been observed 3 times in the current beta version.
After running the app for 2-3 days, the error pattern has so far occurred in the morning.

 🇩🇪  **Erwartungshaltung**:
▫️ Fehlerursachen-Analyse
▫️ Ermittlung der Grundursache
▫️ Implementierung einer dauerhaften Abstellmaßnahme (Problemlösung)
▫️ Optimierung (Verbesserung) der App

🇬🇧  **Expectations**:
▫️ Root cause analysis
▫️ Root cause Determination
▫️ Implementation of a PCA (permanent corrective action) (problem solution)
▫️ Optimisation (improvement) of the application

**Comment by Danswar** [comment]
@Wendel-BS danke für die ausführliche Beschreibung, ich habe Code hinzugefügt, um die Wiederverbindungen zu verbessern (und übermäßige Fehlermeldungen zu entfernen), aber es scheint, dass die Hintergrundzyklen auf Mac und iPhone unterschiedlich funktionieren und den von Ihnen erwähnten Fehler erzeugen, ich werde mir das genauer ansehen. 

Da die Electrum-Server öffentlich sind und von Dritten verwaltet werden, können sie uns leider jederzeit rausschmeißen, aber wir können sicherlich nach besseren Möglichkeiten suchen, die Verbindung wiederherzustellen. Ich werde mich darum kümmern.

**Original message**

@Wendel-BS thanks for the detailed description, I've added code to improve reconnections (plus removing excessive error messages), but it seems the background cycles work differently on Mac and iPhone generating the bug that you pointed out, I'll have a closer look at this. 

Unfortunately, since electrum servers are public, managed by third parties, they can kick us out at any time, but we can certainly look at better ways to reconnect. I'll work it out.
